-- 27강 — identity 개념 (generated always as identity + 직접 값 넣기 에러)
--
-- generated always as identity = 그 컬럼(보통 id)을 DB가 자동으로 순차 생성(1,2,3...).
--   MySQL의 AUTO_INCREMENT와 같은 역할, SQL 표준 방식.
--
-- 두 모드:
--   generated always as identity     : 자동 O, 직접 입력 X(에러) ← 엄격/안전, 국룰
--   generated by default as identity  : 자동 O, 직접 입력 O
--
-- always 컬럼에 직접 값 넣으면:
--   ERROR: cannot insert a non-DEFAULT value into column "id"

drop table if exists demo_identity;

create table demo_identity (
    id   bigint generated always as identity,
    name text
);

-- id 없이 넣기 → 1, 2, 3 자동
insert into demo_identity (name) values ('a'), ('b'), ('c');

select * from demo_identity;

-- id 직접 넣기 → 에러
-- insert into demo_identity (id, name) values (100, 'x');
